name: Build and Push

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: webjobslinuxacr
  RG: webjobs-linux-rg
  SITE_NAME: webjobs-linux-web-app-container

concurrency:
  group: container-${{ github.event.number || github.ref }}
  cancel-in-progress: true  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker image
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login
        run: az acr login --name ${{ env.REGISTRY_NAME }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_NAME }}.azurecr.io/webjob-linux-docker
          tags: type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./WebApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish WebJobs
        run: |
          dotnet publish -c Release -o ./publish/app_data/Jobs/Triggered/webjob-triggered ./WebJobTriggered/WebJobTriggered.csproj
          dotnet publish -c Release -o ./publish/app_data/Jobs/Continuous/webjob-continuous ./WebJobContinuous/WebJobContinuous.csproj

      - name: Deploy WebJobs
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.SITE_NAME }}
          package: './publish'

      - name: Deploy WebApi
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.SITE_NAME }}
          images: ${{ steps.meta.outputs.tags }}
