name: Build and Push

on:
    push:
        branches:
        - main
          
env:
    REGISTRY_NAME: webjobslinuxacr

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Push Docker image

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Azure
          uses: azure/login@v2
          with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
             
        - name: Docker login
          run: az acr login --name ${{ env.REGISTRY_NAME }}
          
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
              images: ${{ env.REGISTRY_NAME }}.azureacr.io/webjob-linux-docker          

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./WebApi/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}