name: Build and Push

on:
  push:
    branches:
      - main

env:
  # AZURE_CORE_OUTPUT: none
  RG: webjobs-linux-rg
  SITE_NAME: webjobs-linux-web-app

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy WebSite

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish WebApi
        run: dotnet publish -c Release -o ./publish ./WebApi/WebApi.csproj

      - name: Deploy WebApi
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ env.SITE_NAME }}
          package: './publish'
